### ISSUE TITLE
runtime error on 32bit arch

### ISSUE THREAD

**Issue by egorenar** [rmcgibbo/async-priority-channel#78]
Hello,

it seems this crate doesn't support 32bit archs.

```
❯ watchexec -- ls
thread 'main' panicked at /home/egorenar/Repositories/openwrt-rel/dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-priority-channel-0.1.0/src/awaitable_atomics.rs:34:43:
attempt to shift left with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This `(1 << 63) - 1` panics on a 32bit ARM arch.

Reproduced with `watchexec`.

**Comment by rmcgibbo** [comment]
Would you be able to test https://github.com/rmcgibbo/async-priority-channel/pull/79?

**Comment by egorenar** [comment]
Tested your fix, looks good! Everything works.
Thanks!

**Comment by rmcgibbo** [comment]
Great, marking this as closed.

**Comment by passcod** [comment]
Thanks! Could you publish 0.2.0 to crates.io?

**Comment by rmcgibbo** [comment]
Sorry for the delay. Version 0.2.0 is published now to crates.io.
